<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Neuroma</AssemblyName>
    <RootNamespace>Neuroma</RootNamespace>
    <Version>0.9.0</Version>
    <ApplicationIcon>..\..\assets\Neuroma.ico</ApplicationIcon>
    <Authors>d-b-w-gain</Authors>
    <Description>A fast, distraction-free EPUB reader for the terminal.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Spectre.Console.ImageSharp" Version="0.57.2" />
  </ItemGroup>
</Project>
