<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Neuroma</AssemblyName>
    <RootNamespace>Neuroma</RootNamespace>
    <Version>0.1.1</Version>
    <Authors>d-b-w-gain</Authors>
    <Description>A fast, distraction-free EPUB reader for the terminal.</Description>
  </PropertyGroup>
</Project>
